### ISSUE TITLE
Error: Certificate verify failed 

### ISSUE THREAD

**Issue by kmruddy** [vmware/vsphere-automation-sdk-ruby#31]
Cloning and setting up a new system resulted in the below message when trying to authenticate to the vCenter Server. 

```
kruddy-m03:samples kyleruddy$ bin/run_sample connection -l vcsa01.corp.local -u 'administrator@vsphere.local' -p 'password' –-insecure
ruby -I/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib -I/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk -I/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/samples/lib lib/sample/workflow/connection_workflow.rb -l vcsa01.corp.local -u administrator@vsphere.local -p password –-insecure
I, [2017-11-03T16:41:35.083149 #13465] INFO -- vAPI Sample Framework: Connecting to lookup service: https://vcsa01.corp.local/lookupservice/sdk
D, [2017-11-03T16:41:35.088350 #13465] DEBUG -- : HTTPI GET request to vcsa01.corp.local (net_http)
D, [2017-11-03T16:41:35.929884 #13465] DEBUG -- : HTTPI POST request to vcsa01.corp.local (net_http)
D, [2017-11-03T16:41:36.667003 #13465] DEBUG -- : HTTPI POST request to vcsa01.corp.local (net_http)
I, [2017-11-03T16:41:37.431177 #13465] INFO -- vAPI Connection Workflow: Getting SSO token (https://vcsa01.corp.local/sts/STSService/vsphere.local)...
D, [2017-11-03T16:41:37.432541 #13465] DEBUG -- : HTTPI GET request to vcsa01.corp.local (net_http)
D, [2017-11-03T16:41:38.180928 #13465] DEBUG -- : HTTPI POST request to vcsa01.corp.local (net_http)
I, [2017-11-03T16:41:38.930811 #13465] INFO -- vAPI Connection Workflow: Login to VAPI endpoint (https://vcsa01.corp.local:443/api) using token...
E, [2017-11-03T16:41:39.434234 #13465] ERROR -- vAPI Connection Workflow: problem running sample
E, [2017-11-03T16:41:39.434401 #13465] ERROR -- vAPI Connection Workflow: SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:876:in `start'
/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib/vapi/protocol/client/rpc/http_provider.rb:42:in `do_request'
/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib/vapi/protocol/client/msg/json_provider.rb:36:in `invoke'
/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib/vapi/bindings/service.rb:43:in `invoke_with_info'
/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/com/vmware/cis.rb:141:in `create'
lib/sample/workflow/connection_workflow.rb:64:in `execute'
/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/samples/lib/sample/framework/sample_base.rb:200:in `run'
/Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/samples/lib/sample/framework/sample_base.rb:72:in `main'
lib/sample/workflow/connection_workflow.rb:82:in `<main>'
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:876:in `start'
from /Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib/vapi/protocol/client/rpc/http_provider.rb:42:in `do_request'
from /Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib/vapi/protocol/client/msg/json_provider.rb:36:in `invoke'
from /Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/runtime/lib/vapi/bindings/service.rb:43:in `invoke_with_info'
from /Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/sdk/com/vmware/cis.rb:141:in `create'
from lib/sample/workflow/connection_workflow.rb:64:in `execute'
from /Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/samples/lib/sample/framework/sample_base.rb:200:in `run'
from /Users/kyleruddy/GitHub/vsphere-automation-sdk-ruby/client/samples/lib/sample/framework/sample_base.rb:72:in `main'
from lib/sample/workflow/connection_workflow.rb:82:in `<main>'
```

I went ahead and rolled my jump box’s snapshot back, imported the vCenter cert and went through the pre-reqs again. Same issue. 

However, oddly enough, if I ran the command without the -k option then ran it again with the -k option within the span of about 5 seconds it would work about 95% of the time.

**Comment by jrgarcia** [comment]
Closing as this is no longer relevant due to the changes made to the SDK. Please reopen if this is still an issue.
