### ISSUE TITLE
Changing boot type api hangs indefinitely 

### ISSUE THREAD

**Issue by JerrodCarpenter** [vmware/vsphere-automation-sdk-ruby#59]
## Describe the bug

After upgrading to vCenter `6.7`, we're seeing this hang indefinitely on vsphere-automation-sdk-ruby `0.3.0`. When I check vCenter, the task completes almost immediately; but hangs via the API.

## How to reproduce

```ruby
configuration = VSphereAutomation::Configuration.new.tap do |c|
  c.host = @name
  c.username = @user
  c.password = @pass
  c.scheme = 'https'
  c.verify_ssl = false
  c.verify_ssl_host = false
end

@rest = VSphereAutomation::ApiClient.new(configuration)
VSphereAutomation::CIS::SessionApi.new(@rest).create('')

spec = { spec: { enter_setup_mode: false, efi_legacy_boot: false, type: 'EFI' } }
VSphereAutomation::VCenter::VmHardwareBootApi.new(@rest).update(<VM ID>, spec)
```

## Expected behavior

Should respond when the task has completed in vCenter.

## Versions

**Dev Environment:**

* Ruby: `2.4.1` & `2.6.3`
* vSphere Automation SDK: `0.3.0`
* OS: macOS and CentOS

## Additional notes

_Add any other notes about the problem here._

**Comment by jrgarcia** [comment]
Thanks for opening this, I'll take a look as soon as I can.

**Comment by JerrodCarpenter** [comment]
I upgraded to `0.4.3` and I'm seeing this exception when attempting to deploy an OVF:

```ruby
16: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/vsphere-automation-vcenter-0.4.3/lib/vsphere-automation-vcenter/api/ovf_library_item_api.rb:82:in `deploy'
15: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/vsphere-automation-vcenter-0.4.3/lib/vsphere-automation-vcenter/api/ovf_library_item_api.rb:123:in `deploy_with_http_info'
14: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/vsphere-automation-runtime-0.4.3/lib/vsphere-automation-runtime/api_client.rb:71:in `call_api'
13: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ruby-ntlm-0.0.4/lib/ntlm/http.rb:22:in `request'
12: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1470:in `request'
11: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:920:in `start'
10: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
 9: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ruby-ntlm-0.0.4/lib/ntlm/http.rb:22:in `request'
 8: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1479:in `request'
 7: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
 6: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
 5: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
 4: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
 3: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
 2: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
 1: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

Should I create a new ticket for this?

**Comment by jrgarcia** [comment]
@JerrodCarpenter Please do. I think I can fix that issue pretty quickly.
