### ISSUE TITLE
Net::ReadTimeout on OVF deploy

### ISSUE THREAD

**Issue by JerrodCarpenter** [vmware/vsphere-automation-sdk-ruby#60]
## Describe the bug

When attempting to deploy an OVF, we receive a `Net::ReadTimeout`

Stack trace:
```ruby
16: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/vsphere-automation-vcenter-0.4.3/lib/vsphere-automation-vcenter/api/ovf_library_item_api.rb:82:in `deploy'
15: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/vsphere-automation-vcenter-0.4.3/lib/vsphere-automation-vcenter/api/ovf_library_item_api.rb:123:in `deploy_with_http_info'
14: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/vsphere-automation-runtime-0.4.3/lib/vsphere-automation-runtime/api_client.rb:71:in `call_api'
13: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ruby-ntlm-0.0.4/lib/ntlm/http.rb:22:in `request'
12: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1470:in `request'
11: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:920:in `start'
10: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
 9: from /.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ruby-ntlm-0.0.4/lib/ntlm/http.rb:22:in `request'
 8: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1479:in `request'
 7: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
 6: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
 5: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
 4: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
 3: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
 2: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
 1: from /.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

## How to reproduce

```ruby
configuration = VSphereAutomation::Configuration.new.tap do |c|
  c.host = @name
  c.username = @user
  c.password = @pass
  c.scheme = 'https'
  c.verify_ssl = false
  c.verify_ssl_host = false
end

@rest = VSphereAutomation::ApiClient.new(configuration)
VSphereAutomation::CIS::SessionApi.new(@rest).create('')

# host, folder, cluster, and datastore are objects that wrap rbvmomi counterpart objects.
# id is a method that essentially calls _ref on the underlying rbvmomi object.
# I can provide examples of these id values, but they appear to be correct.
target = VSphereAutomation::VCenter::VcenterOvfLibraryItemDeploymentTarget.new(
  resource_pool_id: cluster.resourcePool._ref, host_id: host.id, folder_id: folder.id
)
deploy = VSphereAutomation::VCenter::VcenterOvfLibraryItemResourcePoolDeploymentSpec.new(
  name: 'name', accept_all_EULA: true, storage_provisioning: true, default_datastore_id: datastore.id
)
VSphereAutomation::VCenter::VcenterOvfLibraryItemDeploy.new(target: target, deployment_spec: deploy)
result = VSphereAutomation::VCenter::OvfLibraryItemApi.new(@rest).deploy(<ID of OVF>, config).value
```

## Expected behavior

I'd expect the OVF to be deployed without error.

## Versions

**Dev Environment:**

* Ruby: `2.6.3`
* vSphere Automation SDK: `0.4.3`
* OS: macOS `10.14.6`

## Additional notes

_Add any other notes about the problem here._

**Comment by jrgarcia** [comment]
I'm still looking into this. I'm not able to reproduce this error, but I am getting another error (almost immediately which is why I'm not getting to a read timeout). What version of vCenter is this occurring on?

I'm going to go ahead and push an option to set the timeout. It won't affect anyone who doesn't use it, but will allow you to override the default. In the meantime, that may fix it for you.

**Comment by jrgarcia** [comment]
I pushed out a new version to RubyGems (v0.4.4). When creating your configuration you can configure a timeout now. For example,
```ruby
configuration = VSphereAutomation::Configuration.new.tap do |c|
  c.timeout = 100000
  c.host = @name
  c.username = @user
  c.password = @pass
  c.scheme = 'https'
  c.verify_ssl = false
  c.verify_ssl_host = false
end
```
That will allow the timeout to last longer so the deploy can finish. I think that should fix your problem. If not, let me know what happens and I'll continue looking into it. Sorry for the wait on this!

**Comment by JerrodCarpenter** [comment]
This worked for me, I appreciate the swift response!

Upgrading to `0.4.4` took care of this issue as well: https://github.com/vmware/vsphere-automation-sdk-ruby/issues/59

**Comment by jrgarcia** [comment]
@JerrodCarpenter Glad to hear things are working! Do you mind if I close both of these issues?

**Comment by JerrodCarpenter** [comment]
Yep that works for me. As an aside, I've read over your contribution guidelines and understand that a lot of this is generated, but I'd like to learn and contribute to this project if things like this pop up in the future. You have any tips on getting started in that regard?

**Comment by jrgarcia** [comment]
@JerrodCarpenter I’ll add some documentation to show how people can contribute next week. I would definitely welcome any contributions!
