### ISSUE TITLE
Content type text/html not supported 

### ISSUE THREAD

**Issue by EleanorRigby** [vmware/vsphere-automation-sdk-ruby#68]
## Describe the bug

When trying to open a new connection through session API

`session_api = VSphereAutomation::CIS::SessionApi.new(api_client)`

The API client errors out saying `Content-Type is not supported: text/html` 
in vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:159:in `deserialize'

## How to reproduce

vCenter version awaited from customer.

Used automation-sdk version 0.1.0

ruby 2.4.2

```ruby
# minimal code to reproduce issue
```

## Expected behavior
Error should not occur

## Versions

**Dev Environment:**

* Ruby: 2.4.2
* vSphere Automation SDK: 0.1.0
* OS: Linux Ubuntu Xenial/Trusty

## Additional notes
```
Rescued Unknown: Content-Type is not supported: text/html. backtrace: /var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:159:in `deserialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:71:in `call_api'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:61:in `create_with_http_info'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:26:in `create'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/attach_tag_to_vm.rb:108:in `InitializeConnection'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/cloud.rb:128:in `initialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `new'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `initialize'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `new'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `block in <top (required)>'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:87:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:43:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2020-03-17T16:05:15.868370 #25230]  INFO -- [req_id cpi-871039]: Starting info...
D, [2020-03-17T16:05:15.877191 #25230] DEBUG -- [req_id cpi-871039]: Running method 'RetrieveServiceContent'...
D, [2020-03-17T16:05:15.974004 #25230] DEBUG -- [req_id cpi-871039]: Running method 'Login'...
I, [2020-03-17T16:05:16.137140 #25230]  INFO -- [req_id cpi-871039]: Finished info in 0.27 seconds
Rescued Unknown: Content-Type is not supported: text/html. backtrace: /var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:159:in `deserialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:71:in `call_api'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:61:in `create_with_http_info'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:26:in `create'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/attach_tag_to_vm.rb:108:in `InitializeConnection'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/cloud.rb:128:in `initialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `new'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `initialize'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `new'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `block in <top (required)>'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:87:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:43:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2020-03-17T16:05:16.347791 #25256]  INFO -- [req_id cpi-361735]: Starting info...
D, [2020-03-17T16:05:16.352072 #25256] DEBUG -- [req_id cpi-361735]: Running method 'RetrieveServiceContent'...
D, [2020-03-17T16:05:16.438042 #25256] DEBUG -- [req_id cpi-361735]: Running method 'Login'...
I, [2020-03-17T16:05:16.585658 #25256]  INFO -- [req_id cpi-361735]: Finished info in 0.24 seconds
Rescued Unknown: Content-Type is not supported: text/html. backtrace: /var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:159:in `deserialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:71:in `call_api'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:61:in `create_with_http_info'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:26:in `create'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/attach_tag_to_vm.rb:108:in `InitializeConnection'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/cloud.rb:128:in `initialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `new'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `initialize'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `new'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `block in <top (required)>'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:87:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:43:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2020-03-17T16:05:26.960502 #25539]  INFO -- [req_id cpi-834904]: Starting create_vm...
D, [2020-03-17T16:05:26.962530 #25539] DEBUG -- [req_id cpi-834904]: Running method 'RetrieveServiceContent'...
D, [2020-03-17T16:05:27.015440 #25539] DEBUG -- [req_id cpi-834904]: Running method 'Login'...
I, [2020-03-17T16:05:27.124365 #25539]  INFO -- [req_id cpi-834904]: Finished create_vm in 0.16 seconds
Rescued Unknown: Content-Type is not supported: text/html. backtrace: /var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:159:in `deserialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-vcenter-0.1.0/lib/vsphere-automation-vcenter/api_client.rb:71:in `call_api'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:61:in `create_with_http_info'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/vsphere-automation-cis-0.1.0/lib/vsphere-automation-cis/api/session_api.rb:26:in `create'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/attach_tag_to_vm.rb:108:in `InitializeConnection'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere/cloud.rb:128:in `initialize'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `new'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/cloud/vsphere.rb:92:in `initialize'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `new'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:38:in `block in <top (required)>'
/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:87:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:43:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/a53749c688f6ffcefdcb0051cf5716fa4acb2a76/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'/var/vcap/data/packages/vsphere_cpi/867e8ca374165990ba78024886d77673ecd871f4/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2020-03-17T16:05:26.979002 #25439]  INFO -- [req_id cpi-158996]: Starting create_vm...
D, [2020-03-17T16:05:26.980951 #25439] DEBUG -- [req_id cpi-158996]: Running method 'RetrieveServiceContent'...
D, [2020-03-17T16:05:27.031502 #25439] DEBUG -- [req_id cpi-158996]: Running method 'Login'...
I, [2020-03-17T16:05:27.147567 #25439]  INFO -- [req_id cpi-158996]: Finished create_vm in 0.17 seconds
```

**Comment by EleanorRigby** [comment]
cc: @SanikaGawhane @ktchen14

**Comment by EleanorRigby** [comment]
@jrgarcia : Any idea why would VC return a `text/html` instead of `application/json`? I have not seen this in our VMware dev pipelines but the customer is reporting seeing it.

**Comment by swagataroy** [comment]
vCenter Version is 6.5.0.30000 Build 14020092

**Comment by jrgarcia** [comment]
@EleanorRigby The only instance where this would be likely to happen would be if the configuration object is misconfigured. Can you send me what is being used for the configuration? It doesn't appear that it would change anything for this particular issue, but I would also suggest using a newer version than `v0.1.0`.

**Comment by EleanorRigby** [comment]
```
         configuration = VSphereAutomation::Configuration.new.tap do |config|
           config.host = cloud_config.vcenter_host
           config.username = cloud_config.vcenter_user
           config.password = cloud_config.vcenter_password
           config.scheme = 'https'
           config.verify_ssl = false
           config.verify_ssl_host = false
           config.logger = logger
           config.debugging = false
        end
        api_client = VSphereAutomation::ApiClient.new(configuration)
        api_client.default_headers['Authorization'] = configuration.basic_auth_token
        session_api = VSphereAutomation::CIS::SessionApi.new(api_client)
        session_id = session_api.create('').value
        api_client.default_headers['vmware-api-session-id'] = session_id
        api_client
```

**Comment by EleanorRigby** [comment]
Above is config object and the perm link for code is : https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/882f90114b67332c94e1ba83023ef3de9508f15b/src/vsphere_cpi/lib/cloud/vsphere/attach_tag_to_vm.rb#L94

**Comment by jrgarcia** [comment]
@EleanorRigby That looks correct. What is the value of `cloud_config.vcenter_host`? The most likely culprit would be that the host is not set up correctly and it is creating the URL incorrectly. I have seen cases where vCenter will return `text/html` in cases of making a call that results in a server-side error.

**Comment by EleanorRigby** [comment]
@jrgarcia : I think that info is on customer env and will need to be fetched. 

@swagataroy : Can we get what was vcenter_host set to in cpi config?

**Comment by EleanorRigby** [comment]
@jrgarcia : Do you think presence of `http/s` scheme or trailing `/` can cause the problem?

**Comment by jrgarcia** [comment]
@EleanorRigby The scheme should be correct as long as their vCenter is actually available on `https`, which hopefully it is. It is concerning that SSL verification is set to `false` by default. That's a security issue. I'm not sure if a trailing `/` alone would cause an issue, but ideally the host would be nothing more than the hostname with no scheme or slashes. Just a hostname.
